apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-system-frontend
spec:
  selector:
    matchLabels:
      app: assessment-system-frontend

  replicas: 3
  template:
    metadata:
      labels:
        app: assessment-system-frontend
    spec:
      containers:
        - name: assessment-system-frontend
          image: us.gcr.io/my-project-1529917597814/assessment-system-frontend
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: assessment-system-frontend-service
  labels:
    name: assessment-system-frontend-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: assessment-system-frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: assessment-system-frontend-service
              servicePort: 80



