apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: assessment-system-frontend
build:
  artifacts:
  - image: mananmistry/ict-assessment-system-frontend
deploy:
  kubectl:
    manifests:
    - k8s-assessment-system-frontend.yaml
